name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: sinkingcircle
          outputs: github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: github-contribution-grid-snake.svg
